Trademarks
IBM/zowe-cli-cics-deploy-plugin pull request #298
Opened 2019-06-21 14:42 UTC by tasha-m-k

2019-06-21 15:11 UTC, cxharris submitted a review, later dismissed

2019-06-21 18:09 UTC, markcocker requested changes
Do instances of "Java" need to be "Java™"?
I see headings and sub-headings having (R) marks, but should they be?
Also see review comments.

2019-06-21 18:09 UTC, markcocker commented on README.md
> +This project provides a plug-in for [Zowe CLI](https://github.com/zowe/zowe-cli) to deploy applications developed on a workstation to IBM® CICS® Transaction Server for z/OS® (CICS). It aims to provid
I thought only the first instance of a registered trademark text needed to have the ® mark. I see two instances marked here. Also applies to other files.

2019-06-21 18:09 UTC, markcocker commented on docs/_data/sidebars/cdp_sidebar.yml
> +    - title: Zowe CLI CICS® deploy plug-in
Should the side navigation bar have any registered marks? I see this as equivalent to the knowledge centre “Table of Contents” nav bar and it does not have any marks.

2019-06-21 18:09 UTC, markcocker commented on docs/pages/cdp/cdp-Common-Errors.md
> +* Ask your CICS® Systems Programmer to check that the CMAS for the current CICSPlex® is alive and that CPSM is working properly.
Suggest "current CICSPlex"  > "cicsplex"

2019-06-21 18:09 UTC, markcocker commented on docs/pages/cdp/cdp-Creating-Zowe-CLI-profiles.md
> +| cics-plex | CPSM CICSplex® name. This will typically be set to the same as cicsplex in the cics-deploy profile. |
Is “CICSplex” (note casing)  a registered trademark? For example https://www.ibm.com/support/knowledgecenter/SSGMCP_5.5.0/configuring/parallel-sysplex/sysplex_cicsplex_synergies.html does not show a mark on the first instance off “CICSplex” but does for first instance of “CICSPlex®”

2019-06-21 18:09 UTC, markcocker commented on docs/_config.yml
> +topnav_title: Zowe CLI CICS® deploy plug-in
Is trademarking page titles necessary? I don't see this being done in the CICS KC.

2019-06-21 18:09 UTC, markcocker commented on docs/pages/cdp/cdp-Log-and-trace-files.md
> +If you are familiar with the z/OS® environment, you can often find some useful diagnostics by accessing the JES job log associated with the CICS® region you deployed to.  The `cics-deploy push` comma
Can you pls remove double and tripple spaces after full stops. I realise HTML will collapse them but they are unnecessary.

2019-06-24 10:27 UTC, markcocker approved these changes
Thanks. Changes look good.

2019-06-24 10:28 UTC, merged