Release/1.0.0
IBM/zowe-cli-cics-deploy-plugin pull request #302
Opened 2019-06-25 13:33 UTC by ChrisPark89

2019-06-25 14:10 UTC, markcocker requested changes
Can you update "[Unreleased]" in CHANGELOG.md to 1.0 and add anything more to the list that you think would be useful.

2019-06-25 14:33 UTC, ChrisPark89 commented
> Can you update "[Unreleased]" in CHANGELOG.md to 1.0 and add anything more to the list that you think would be useful.

done

2019-06-25 14:45 UTC, pcoop approved these changes

2019-06-25 14:49 UTC, matthewpwilson approved these changes

2019-06-25 15:00 UTC, markcocker approved these changes

2019-06-27 09:30 UTC, cxharris approved these changes

2019-06-27 09:32 UTC, merged